kind: pipeline
type: docker
name: ci-cd-pipeline

steps:
  - name: build-backend
    image: node:20.14.0-buster
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: AIvaluatedb
    commands:
      - cd app/aivaluate/backend
      - npm install
      - sh -c "while ! nc -z $DB_HOST $DB_PORT; do sleep 1; done"
      - npm test

  - name: build-frontend
    image: node:20.14.0-buster
    commands:
      - cd app/aivaluate/frontend
      - npm install
      - npm run build

services:
  - name: database
    image: postgres
    environment:
      POSTGRES_DB: AIvaluatedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

trigger:
  branch:
    - master
    - development
  event:
    - pull_request
